# Generated by Django 5.2.5 on 2025-08-25 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Audit',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('action', models.TextField()),
                ('affected_table', models.CharField(db_column='tabela_afetada', max_length=100)),
                ('record_id', models.IntegerField(db_column='id_registro')),
                ('data_before', models.JSONField(blank=True, db_column='dados_antes', null=True)),
                ('data_after', models.JSONField(blank=True, db_column='dados_depois', null=True)),
            ],
            options={
                'verbose_name': 'Audit',
                'verbose_name_plural': 'Audits',
                'db_table': 'auditorias',
            },
        ),
        migrations.CreateModel(
            name='Backup',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('backup_type', models.CharField(db_column='tipo', max_length=50)),
                ('storage_location', models.TextField(db_column='local_armazenamento')),
                ('status', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Backup',
                'verbose_name_plural': 'Backups',
                'db_table': 'backups',
            },
        ),
        migrations.CreateModel(
            name='FinancialReport',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('start_date', models.DateField(db_column='data_inicio')),
                ('end_date', models.DateField(db_column='data_fim')),
                ('total_revenue', models.DecimalField(blank=True, db_column='receita_total', decimal_places=2, max_digits=12, null=True)),
                ('total_expense', models.DecimalField(blank=True, db_column='despesa_total', decimal_places=2, max_digits=12, null=True)),
                ('balance', models.DecimalField(blank=True, db_column='saldo', decimal_places=2, max_digits=12, null=True)),
                ('report_type', models.CharField(db_column='tipo', max_length=50)),
            ],
            options={
                'verbose_name': 'Financial Report',
                'verbose_name_plural': 'Financial Reports',
                'db_table': 'relatorios_financeiros',
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('module_name', models.CharField(db_column='nome_modulo', max_length=100)),
                ('operational_status', models.CharField(db_column='status_operacional', max_length=30)),
                ('response_time_ms', models.IntegerField(blank=True, null=True)),
                ('last_check', models.DateTimeField(db_column='ultima_verificacao')),
            ],
            options={
                'verbose_name': 'System Status',
                'verbose_name_plural': 'System Statuses',
                'db_table': 'status_sistema',
            },
        ),
    ]
