# Generated by Django 5.2.5 on 2025-08-14 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthProfessional',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('name', models.CharField(max_length=150)),
                ('professional_registry', models.CharField(blank=True, db_column='registro_profissional', max_length=50, null=True)),
                ('specialty', models.CharField(blank=True, db_column='especialidade', max_length=100, null=True)),
                ('position', models.CharField(blank=True, db_column='cargo', max_length=50, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, db_column='telefone', max_length=20, null=True)),
                ('hospital_unit', models.ForeignKey(db_column='unidade_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.hospitalunit')),
            ],
            options={
                'verbose_name': 'Health Professional',
                'verbose_name_plural': 'Health Professionals',
                'db_table': 'profissionais_saude',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('date', models.DateField(db_column='data')),
                ('start_time', models.TimeField(db_column='hora_inicio')),
                ('end_time', models.TimeField(db_column='hora_fim')),
                ('event_type', models.CharField(blank=True, db_column='tipo_evento', max_length=100, null=True)),
                ('is_available', models.BooleanField(db_column='disponibilidade', default=True)),
                ('professional', models.ForeignKey(db_column='profissional_id', on_delete=django.db.models.deletion.CASCADE, to='professionals.healthprofessional')),
            ],
            options={
                'verbose_name': 'Schedule',
                'verbose_name_plural': 'Schedules',
                'db_table': 'agendas',
            },
        ),
    ]
