# Generated by Django 5.2.5 on 2025-08-14 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('stock_quantity', models.IntegerField(db_column='quantidade_estoque', default=0)),
                ('unit_of_measure', models.CharField(blank=True, db_column='unidade_medida', max_length=20, null=True)),
                ('supplier_id', models.IntegerField(blank=True, db_column='fornecedor_id', null=True)),
            ],
            options={
                'verbose_name': 'Supply',
                'verbose_name_plural': 'Supplies',
                'db_table': 'suprimentos',
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('movement_type', models.CharField(db_column='tipo', max_length=20)),
                ('quantity', models.IntegerField()),
                ('professional', models.ForeignKey(db_column='profissional_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='professionals.healthprofessional')),
                ('supply', models.ForeignKey(db_column='suprimento_id', on_delete=django.db.models.deletion.CASCADE, to='inventory.supply')),
            ],
            options={
                'verbose_name': 'Stock Movement',
                'verbose_name_plural': 'Stock Movements',
                'db_table': 'movimentacoes_estoque',
            },
        ),
    ]
