# Generated by Django 5.2.5 on 2025-08-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bed',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('number', models.CharField(max_length=10)),
                ('bed_type', models.CharField(db_column='tipo', max_length=50)),
                ('status', models.CharField(max_length=20)),
                ('occupation_date', models.DateField(blank=True, db_column='data_ocupacao', null=True)),
            ],
            options={
                'verbose_name': 'Bed',
                'verbose_name_plural': 'Beds',
                'db_table': 'leitos',
            },
        ),
        migrations.CreateModel(
            name='Hospitalization',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('entry_date', models.DateField(db_column='data_entrada')),
                ('discharge_date', models.DateField(blank=True, db_column='data_alta', null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Hospitalization',
                'verbose_name_plural': 'Hospitalizations',
                'db_table': 'internacoes',
            },
        ),
        migrations.CreateModel(
            name='HospitalUnit',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('name', models.CharField(max_length=150)),
                ('address', models.TextField(blank=True, db_column='endereco', null=True)),
                ('unit_type', models.CharField(db_column='tipo_unidade', max_length=50)),
                ('contact_info', models.CharField(blank=True, db_column='contato', max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Hospital Unit',
                'verbose_name_plural': 'Hospital Units',
                'db_table': 'unidades_hospitalares',
            },
        ),
    ]
