# Generated by Django 5.2.5 on 2025-08-25 23:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bed',
            name='occupying_patient',
            field=models.ForeignKey(blank=True, db_column='paciente_ocupante_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='bed',
            field=models.ForeignKey(db_column='leito_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.bed'),
        ),
        migrations.AddField(
            model_name='hospitalization',
            name='patient',
            field=models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='bed',
            name='hospital_unit',
            field=models.ForeignKey(db_column='unidade_id', on_delete=django.db.models.deletion.CASCADE, to='infrastructure.hospitalunit'),
        ),
    ]
