# Generated by Django 5.2.5 on 2025-08-14 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_service', '0001_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Teleconsultation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('timestamp', models.DateTimeField(db_column='data_hora')),
                ('video_call_link', models.URLField(db_column='link_videochamada', max_length=500)),
                ('status', models.CharField(max_length=30)),
                ('recording_url', models.URLField(blank=True, db_column='gravacao_url', max_length=500, null=True)),
                ('patient', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('professional', models.ForeignKey(db_column='profissional_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='professionals.healthprofessional')),
            ],
            options={
                'verbose_name': 'Teleconsultation',
                'verbose_name_plural': 'Teleconsultations',
                'db_table': 'teleconsultas',
            },
        ),
        migrations.CreateModel(
            name='TeleconsultationRecord',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('observations', models.TextField(blank=True, null=True)),
                ('medical_record', models.ForeignKey(db_column='prontuario_id', on_delete=django.db.models.deletion.CASCADE, to='patients.medicalrecord')),
                ('prescription', models.ForeignKey(blank=True, db_column='prescricao_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='clinical_service.prescription')),
                ('teleconsultation', models.ForeignKey(db_column='teleconsulta_id', on_delete=django.db.models.deletion.CASCADE, to='telemedicine.teleconsultation')),
            ],
            options={
                'verbose_name': 'Teleconsultation Record',
                'verbose_name_plural': 'Teleconsultation Records',
                'db_table': 'registros_teleconsulta',
            },
        ),
    ]
