# Generated by Django 5.2.5 on 2025-08-14 00:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('professionals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('name', models.CharField(max_length=150)),
                ('cpf', models.CharField(max_length=14, unique=True)),
                ('birth_date', models.DateField(blank=True, db_column='data_nascimento', null=True)),
                ('gender', models.CharField(blank=True, db_column='sexo', max_length=1, null=True)),
                ('phone', models.CharField(blank=True, db_column='telefone', max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=100, null=True)),
                ('address', models.TextField(blank=True, db_column='endereco', null=True)),
                ('emergency_details', models.TextField(blank=True, db_column='dados_emergencia', null=True)),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
                'db_table': 'pacientes',
            },
        ),
        migrations.CreateModel(
            name='MedicalRecord',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('general_observations', models.TextField(blank=True, db_column='observacoes_gerais', null=True)),
                ('responsible_physician', models.ForeignKey(db_column='medico_responsavel_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='professionals.healthprofessional')),
                ('patient', models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'verbose_name': 'Medical Record',
                'verbose_name_plural': 'Medical Records',
                'db_table': 'prontuarios',
            },
        ),
    ]
