# Generated by Django 5.2.5 on 2025-08-14 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('appointment_type', models.CharField(db_column='tipo', max_length=50)),
                ('timestamp', models.DateTimeField(db_column='data_hora')),
                ('reason', models.TextField(blank=True, db_column='motivo', null=True)),
                ('observations', models.TextField(blank=True, db_column='observacoes', null=True)),
                ('status', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'Appointment',
                'verbose_name_plural': 'Appointments',
                'db_table': 'atendimentos',
            },
        ),
        migrations.CreateModel(
            name='Consultation',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('specialty', models.CharField(db_column='especialidade', max_length=100)),
                ('location', models.CharField(blank=True, db_column='local', max_length=100, null=True)),
                ('consultation_type', models.CharField(blank=True, db_column='tipo_consulta', max_length=20, null=True)),
                ('status', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'verbose_name': 'Consultation',
                'verbose_name_plural': 'Consultations',
                'db_table': 'consultas',
            },
        ),
        migrations.CreateModel(
            name='DigitalReceipt',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('expiration_date', models.DateField(blank=True, db_column='data_validade', null=True)),
                ('pdf_file', models.TextField(db_column='arquivo_pdf', help_text='Path or link to the PDF file.')),
            ],
            options={
                'verbose_name': 'Digital Receipt',
                'verbose_name_plural': 'Digital Receipts',
                'db_table': 'receitas_digitais',
            },
        ),
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('exam_type', models.CharField(db_column='tipo_exame', max_length=100)),
                ('request_date', models.DateField(db_column='data_solicitacao')),
                ('completion_date', models.DateField(blank=True, db_column='data_realizacao', null=True)),
                ('result', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Examination',
                'verbose_name_plural': 'Examinations',
                'db_table': 'exames',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(db_column='id', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_column='updated_at')),
                ('prescription_text', models.TextField(db_column='texto_prescricao')),
                ('digital_signature', models.TextField(blank=True, db_column='assinatura_digital', null=True)),
            ],
            options={
                'verbose_name': 'Prescription',
                'verbose_name_plural': 'Prescriptions',
                'db_table': 'prescricoes',
            },
        ),
    ]
