# Generated by Django 5.2.5 on 2025-08-25 23:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinical_service', '0001_initial'),
        ('patients', '0001_initial'),
        ('professionals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='professional',
            field=models.ForeignKey(db_column='profissional_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='professionals.healthprofessional'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='appointment',
            field=models.ForeignKey(db_column='atendimento_id', on_delete=django.db.models.deletion.CASCADE, to='clinical_service.appointment'),
        ),
        migrations.AddField(
            model_name='digitalreceipt',
            name='patient',
            field=models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='examination',
            name='patient',
            field=models.ForeignKey(db_column='paciente_id', on_delete=django.db.models.deletion.CASCADE, to='patients.patient'),
        ),
        migrations.AddField(
            model_name='examination',
            name='requesting_professional',
            field=models.ForeignKey(db_column='profissional_solicitante_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='professionals.healthprofessional'),
        ),
        migrations.AddField(
            model_name='historicalconsultation',
            name='appointment',
            field=models.ForeignKey(blank=True, db_column='atendimento_id', db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='clinical_service.appointment'),
        ),
        migrations.AddField(
            model_name='historicalconsultation',
            name='history_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='prescription',
            name='appointment',
            field=models.ForeignKey(db_column='atendimento_id', on_delete=django.db.models.deletion.CASCADE, to='clinical_service.appointment'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='professional',
            field=models.ForeignKey(db_column='profissional_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='professionals.healthprofessional'),
        ),
        migrations.AddField(
            model_name='digitalreceipt',
            name='prescription',
            field=models.ForeignKey(db_column='prescricao_id', on_delete=django.db.models.deletion.CASCADE, to='clinical_service.prescription'),
        ),
    ]
